name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username michabirklbauer --password-stdin
        docker build . --file Dockerfile --tag michabirklbauer/apmanewsletter:latest
        docker push michabirklbauer/apmanewsletter:latest
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag michabirklbauer/apmanewsletter:latest michabirklbauer/apmanewsletter:$GIT_SHA
        docker push michabirklbauer/apmanewsletter:$GIT_SHA
